### ISSUE TITLE
npm start not working, generating browser application bundles digital envelope routines::unsupported

### ISSUE THREAD

**Issue by archubbuck** [Azure-Samples/ms-identity-javascript-angular-tutorial#169]
# Issue

> When running `npm start`, the application does not start because it encounters an issue when "generating browser application bundles".

## This issue is for the sample

```console
    - [x] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call a multi-tenant web API
    - [ ] 7-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 7-2) Call a web API using Proof of Possession tokens
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> Clone the repository, `npm install`, fill in the client id and tenant id, then run `npm start`

### Any log messages given by the failure

```
> ms-identity-angular-c1s1@1.0.0 start
> ng serve

- Generating browser application bundles...(node:12048) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
| Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\loader-runner\lib\LoaderRunner.js:111:13)    
    at C:\Users\mm02890\source\repos\angular-ms-identity\node_modules\babel-loader\lib\index.js:59:103
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.2.0
```

### Expected/desired behavior

> The tooling should serve an instance of the application.

### Library version

> Angular: 11.0.9

### Browser and version

> Chrome

### Mention any other details that might be useful

```
C:\Users\mm02890\source\repos\angular-ms-identity>ng version
Your global Angular CLI version (13.3.6) is greater than your local version (11.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.7
Node: 18.2.0
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.2.3
@angular/cli                    11.0.7
@angular/material               11.2.3
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.6
typescript                      4.0.7
```

**Comment by derisen** [comment]
@archubbuck this error seems to be related to Node versions (17+) that are not LTS. Switching to an LTS version would be the quickest solution, but we do need to update our Angular samples eventually (apologies for that, it's in the backlog but we couldn't start on it yet).
