### ISSUE TITLE
Error when starting application: Unsupported digital envelope routines: [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.

### ISSUE THREAD

**Issue by ioxterminal** [Azure-Samples/ms-identity-javascript-angular-tutorial#373]
- [x] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ]   4) Deploy to Azure Storage and App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a multi-tenant web API

- [x] bug report 

### Minimal steps to reproduce

1. Run `npm start` in the project directory. like ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA 
2. Observe the error message.

### Any log messages given by the failure

Generating browser application bundles...(node:34444) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use node --trace-deprecation ... to show where the warning was created)
\ Generating browser application bundles (phase: building)...node:internal/crypto/hash:80
this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:80:19)
at Object.createHash (node:crypto:139:10)
at module.exports (C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\webpack\lib\util\createHash.js:135:53)
at NormalModule._initBuildHash (C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\webpack\lib\NormalModule.js:417:16)
at C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\webpack\lib\NormalModule.js:452:10
at C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\webpack\lib\NormalModule.js:323:13
at C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\loader-runner\lib\LoaderRunner.js:367:11
at C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\loader-runner\lib\LoaderRunner.js:233:18
at context.callback (C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
at C:\onedrive\skripte\git\ms-identity-javascript-angular-tutorial\1-Authentication\1-sign-in\SPA\node_modules\babel-loader\lib\index.js:59:103
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
opensslErrorStack: [
'error:03000086:digital envelope routines::initialization error',
'error:0308010C:digital envelope routines::unsupported'
],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

### Expected/desired behavior

The application should start without errors.

### Library version

Node.js v20.12.2

### Mention any other details that might be useful

The error seems to be related to unsupported digital envelope routines.

**Comment by ioxterminal** [comment]
I solved it by downgrading to Node.js v16.20.2
